### PR TITLE
Ghost tutorial

### PR DESCRIPTION
**Pull request by eskender-f**
This pull request is for testing scripts to maintain the integrity of ghost notebook tutorial.

### CODE REVIEW

**Comment by tesYolan** [comment]
@Eskender-B I would review tomorrow.

**Comment by eskender-f** [comment]
I think, there is a lot I can improve upon...I will see what I can do.

**Comment by amebel** [comment]
@Eskender-B please see [srfi 64](https://www.gnu.org/software/guile/manual/guile.html#SRFI_002d64 ). Maybe you can your wrap your code as  a test-runner for ghost. Once I am done with the ci infrastructure, I will be adding some tooling for general scheme tests using it.

**Comment by tesYolan** [comment]
We would move to the guile-test suite soon, though this pull request had become state. I would merge it and then move to that soon.

**Review by tesYolan — APPROVED** [review]

**Review by tesYolan — APPROVED** [review]

**Comment by amebel** [comment]
@tesYolan no need on the guile-test suite I am working on it now.

**Comment by amebel** [comment]
@tesYolan I guess you mean for this repo when it comes to the guile-test suite, please do so.

**Comment by tesYolan** [comment]
yeah, I mean for this set of tutorials.

**Pull request merged**
